apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sqlserver
  name: sqlserver
spec:
  replicas: 10
  selector:
    matchLabels:
      app: sqlserver
  template:
    metadata:
      labels:
        app: sqlserver
    spec:
      containers:
      - image: mcr.microsoft.com/mssql/server:2019-CU5-ubuntu-18.04
        name: server
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_SA_PASSWORD
          value: "Testing1122"