apiVersion: v1
kind: PersistentVolume
metadata:
  labels: 
    env: test
  annotations:
    pv.kubernetes.io/bound-by-controller: "yes"
    pv.kubernetes.io/provisioned-by: kubernetes.io/azure-disk
    volumehelper.VolumeDynamicallyCreatedByKey: azure-disk-dynamic-provisioner
  finalizers:
  - kubernetes.io/pv-protection
  name: pvc-1
spec:
  accessModes:
  - ReadWriteOnce
  azureDisk:
    cachingMode: ReadOnly
    diskName: kubernetes-dynamic-pvc-3e077288-f3e0-11e9-a5c8-f28d2afe8d41
    diskURI: /subscriptions/fafcfdcb-d2a1-43a6-adbe-ca29842135a3/resourceGroups/MC_containers1_SQLK8sCluster2_eastus/providers/Microsoft.Compute/disks/kubernetes-dynamic-pvc-3e077288-f3e0-11e9-a5c8-f28d2afe8d41
    fsType: ""
    kind: Managed
    readOnly: false
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azure-disk