apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: sqlserver2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: sqlserver2
    spec:
      containers:
      - name: sqlserver2
        image: mcr.microsoft.com/mssql/rhel/server:2019-CU1-rhel-8
        ports:
        - containerPort: 1433
        env:
        - name: SA_PASSWORD
          value: "Testing1122"
        - name: ACCEPT_EULA
          value: "Y"
---
apiVersion: v1
kind: Service
metadata:
  name: sqlserver2-service
spec:
  ports:
  - name: sqlserver2
    port: 1433
    targetPort: 1433
  selector:
    name: sqlserver2
  type: LoadBalancer