apiVersion: v1
kind: Service
metadata:
  name: azuresqledge-service
  labels:
    app: azuresqledge
spec:
  ports:
  - name: azuresqledge
    port: 1433
    targetPort: 1433
  selector:
    name: azuresqledge
  type: LoadBalancer
