apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
spec:
  replicas: 20
  selector:
    matchLabels:
      name: demo
  template:
    metadata:
      labels:
        name: demo
    spec:
      containers:
      - name: demo1
        image: nginx:latest