apiVersion: v1
kind: PersistentVolume
metadata:
  name: sqlsystem-demo-pv
spec:
  capacity:
    storage: 1024Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: pi-nfs-server
    path: "/mnt/nfsshare/sqlsystem"