apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlsystem-demo-pvc
spec:
  volumeName: sqlsystem-demo-pv
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 1024Mi
